# City name
city: Somerville, Massachusetts, USA
# City centerpoint latitude & longitude (default geocoded values set)
city_latitude: None
city_longitude: None

# City's time zone: defaults to the local time zone of computer initializing the city's config file
timezone: America/New_York
# Radius of city's road network from centerpoint in km, required if OSM has no polygon data (defaults to 20km)
city_radius: 20

# The folder under data where this city's data is stored
name: somerville

# If given, limit crashes to after startdate and no later than enddate
# Recommended to limit to just a few years for now
startdate:
enddate:

# The type of predictions to generate, 'segment' is default, 'week' is legacy
level: segment

#################################################################
# Configuration for data standardization

# crash file configurations
crashes_files:
  Motor_Vehicle_Crash_Reports.csv:
    required:
      id: ID
      latitude:
      longitude:
      # If date supplied in single column:
      date_complete: Date
      # If date is separated into year/month/day:
      date_year:
      date_month:
      # Leave date_day empty if not available
      date_day:
      # If time is available and separate from date:
      time:
      # If time specified, time_format is one of:
      # default (HH:MM:SS)
      # seconds (since midnight)
      # military (HHMM)
      time_format:
    optional:
      summary:
      # If the crash file doesn't have a lat/lon, you must give the address field
      # and you will need to run the geocode_batch script - see the README
      address: Location
      vehicles:
      bikes:

# If using legacy 'week' predictions:
# specify year & week on which to predict crashes (best practice is year & week towards the end of your crash data set
# in format [month, year]
time_target: [30, 2017]
# specify how many weeks back to predict in output of train_model
weeks_back: 1

#################################################################
# Configuration for default features

# Default features from open street map. You can remove features you don't want
# Note: we don't support adding features in the config file.
# If there is an additional feature you want from open street map, contact the development team
openstreetmap_features:
  categorical:
    width: Width
    cycleway_type: Bike lane
    signal: Signal
    oneway: One Way
    lanes: Number of lanes
  continuous:
    width_per_lane: Average width per lane


# Configuration for default waze features
waze_features:
  categorical:
    jam: Existence of a jam
  continuous:
    jam_percent: Percent of time there was a jam


